name: Get version
description: |
  Setting version and automatically incrementing the patch version on main

  Required permissions:
    - contents: read
outputs:
  version:
    description: The version
    value: ${{ steps.get_version.outputs.version }}
runs:
  using: composite
  steps:
    - id: get_version
      name: Get version
      shell: bash
      run: $GITHUB_ACTION_PATH/get-version.sh
      env:
        GH_TOKEN: ${{ github.token }}
