name: Set version
description: |
  Attached a tag to the current commit and pushes it

  Required permissions:
    - contents: write
inputs:
  version:
    description: "The version"
    required: true
runs:
  using: composite
  steps:
    - name: Push the new version tag
      shell: bash
      run: |
        set -e

        tagExists=$(git ls-remote origin "refs/tags/${VERSION}")

        if [ -z "$tagExists" ]; then
          echo "Pushing tag $VERSION"
          git config --global user.email "github-actions@sjoedin.se"
          git config --global user.name "GitHub Actions"
          git tag "${VERSION}" -m "Version ${VERSION}"
          git push --tags
        else
          echo "Tag $VERSION already exists, not pushing"
        fi
      env:
        VERSION: ${{ inputs.version }}
